{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "synapse-compress-state.fullname" . }}
  labels:
    app.kubernetes.io/name: synapse-compress-state
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse-compress-state
    spec:
      restartPolicy: Never
      containers:
        - name: compress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--postgres-url=$(DATABASE_URL)"
            - "--chunk-size={{ .Values.cmdArgs.chunkSize }}"
            - "--min-state-groups={{ .Values.cmdArgs.minStateGroups }}"
            {{- if .Values.cmdArgs.progress }}
            - "--progress"
            {{- end }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret.name }}
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.databaseUrlKey }}
                  {{- else }}
                  name: {{ include "synapse-compress-state.fullname" . }}
                  key: DATABASE_URL
                  {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
{{- end }}
