{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "synapse-compress-state.fullname" . }}
  labels:
    app.kubernetes.io/name: synapse-compress-state
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse-compress-state
    spec:
      restartPolicy: Never
      containers:
        - name: compress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - '/bin/sh'
            - '-c'
          args:
            - |
              /usr/local/bin/synapse_auto_compressor \
              -p $DATABASE_URL \
              -c {{ .Values.cmdArgs.chunkSize }} \
              -n {{ .Values.cmdArgs.minStateGroups }}
          envFrom:
            - secretRef:
                {{- if .Values.existingSecret.name }}
                name: {{ .Values.existingSecret.name }}
                {{- else }}
                name: {{ include "synapse-compress-state.fullname" . }}
                {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
{{- end }}
