{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse-compress-state.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ $v | toString | b64enc }}
{{- end }}
