apiVersion: v1
kind: Secret
metadata:
  name: synapse-pgbouncer
  metadata:
    labels:
      app: synapse-pgbouncer
data:
  userlist.txt: |
    {{ .Values.synapse.postgres.user | quote }} {{ .Values.synapse.postgres.password | quote }}
